spring:
  application:
    name: Pickingupreviews
  mail:
    host: smtp.gmail.com
    port: 587
    username: kavindusandeepa815@gmail.com
    password: bvtyhafxqqogletv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/pickingupreviews_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: KAvindu@#076
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

google:
  client:
    id: 1017515306667-dq1kkvunpaqae8u5va22rpn512dih5tr.apps.googleusercontent.com

cors:
  allowed:
    origins: http://localhost:4200

app:
  url: http://localhost:4200
